name: Build GBA ROM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: addnab/docker-run-action@v3
        with:
          image: devkitpro/devkitarm:latest
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            make clean
            make all || true

      - name: List build outputs
        run: |
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geodash-gba-rom
          path: |
            **/*.gba





